# Generated by Django 3.2.12 on 2023-09-12 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_type', models.CharField(choices=[('1', 'Mountain Bikes'), ('2', 'Electric Bicycles'), ('3', 'Road Bikes'), ('4', 'Hybrid Bikes'), ('5', 'Folding Bikes'), ('6', 'Comfort Bikes')], max_length=50)),
                ('age_range', models.CharField(choices=[('1', 'three-five'), ('2', 'five-nine'), ('3', 'nine-forteen'), ('4', 'forteen-ninteen'), ('5', 'ninteen-twentyfive'), ('6', '25_above')], max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('noOfSpeed', models.CharField(choices=[('1', 'one'), ('2', 'two'), ('3', 'three'), ('4', 'four'), ('5', 'five'), ('6', 'six')], max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('file_image', models.FileField(upload_to='e_commerce_app/static/Uploaded_images')),
            ],
        ),
    ]
