# Generated by Django 3.2.12 on 2023-09-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0004_alter_seller_register_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller_register',
            name='photo',
            field=models.FileField(upload_to='e_commerce_app/static/profile_photos'),
        ),
    ]
