# Generated by Django 3.2.12 on 2023-09-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0007_alter_seller_register_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_product',
            name='age_range',
            field=models.CharField(choices=[('three-five', 'three-five'), ('five-nine', 'five-nine'), ('nine-forteen', 'nine-forteen'), ('forteen-ninteen', 'forteen-ninteen'), ('ninteen-twentyfive', 'ninteen-twentyfive'), ('25_above', '25_above')], max_length=50),
        ),
        migrations.AlterField(
            model_name='add_product',
            name='bike_type',
            field=models.CharField(choices=[('Mountain Bikes', 'Mountain Bikes'), ('Electric Bicycles', 'Electric Bicycles'), ('Road Bikes', 'Road Bikes'), ('Hybrid Bikes', 'Hybrid Bikes'), ('Folding Bikes', 'Folding Bikes'), ('Comfort Bikes', 'Comfort Bikes')], max_length=50),
        ),
        migrations.AlterField(
            model_name='add_product',
            name='noOfSpeed',
            field=models.CharField(choices=[('one', 'one'), ('two', 'two'), ('three', 'three'), ('four', 'four'), ('five', 'five'), ('six', 'six')], max_length=50),
        ),
    ]
