# Generated by Django 3.2.12 on 2023-09-14 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0008_auto_20230913_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='buyer_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
