# Generated by Django 3.2.12 on 2023-09-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0009_buyer_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer_register',
            name='city',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyer_register',
            name='pincode',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyer_register',
            name='state',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyer_register',
            name='street',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
