# Generated by Django 3.2.12 on 2023-09-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0011_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='description',
            new_name='bike_type',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='product_name',
            new_name='brand',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='color',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlist',
            name='file_image',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlist',
            name='noOfSpeed',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
