# Generated by Django 3.2.12 on 2023-09-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0013_wishlist_prod_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='age_range',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
