# Generated by Django 3.2.12 on 2023-09-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0015_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='delivary_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('order_date', models.DateField(auto_now=True)),
                ('estimated_delivery', models.DateField()),
                ('products', models.CharField(max_length=100)),
                ('total_amount_paid', models.IntegerField()),
            ],
        ),
    ]
