# Generated by Django 3.2.12 on 2023-09-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0016_delivary_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivary_details',
            name='products',
            field=models.FileField(upload_to=''),
        ),
    ]
