# Generated by Django 3.2.12 on 2023-09-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0017_alter_delivary_details_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivary_details',
            name='estimated_delivery',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='delivary_details',
            name='order_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
