# Generated by Django 3.2.12 on 2023-09-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0018_auto_20230928_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivary_details',
            name='address',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='delivary_details',
            name='products',
            field=models.TextField(),
        ),
    ]
