# Generated by Django 3.2.12 on 2023-09-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0019_auto_20230928_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivary_details',
            name='products_image',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
